services:
  app_consumer:
    container_name: express_consumer
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "-r", "tsconfig-paths/register", "dist/app.js"]
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: always